micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - ${CORS_ALLOWED_ORIGIN:`^http(|s):\/\/grails\.org$`}
            - https://grails.github.io/grails-forge-ui
          allowedMethods:
            - GET
  http:
    services:
      github-oauth:
        url: https://github.com
      github-api-v3:
        url: https://api.github.com
grails:
  forge:
      github:
        client-id: ${GITHUB_OAUTH_APP_CLIENT_ID}
        client-secret: ${GITHUB_OAUTH_APP_CLIENT_SECRET}
        token-permissions: public_repo,read:user
gcp:
  http:
    client:
      auth:
        patterns:
          - /analytics/**
