micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - https://grails.github.io
            - https://start.grails.org
          allowedMethods:
            - GET
  http:
    services:
      github-oauth:
        url: https://github.com
      github-api-v3:
        url: https://api.github.com
grails:
  forge:
      github:
        client-id: ${GITHUB_OAUTH_APP_CLIENT_ID}
        client-secret: ${GITHUB_OAUTH_APP_CLIENT_SECRET}
        token-permissions: public_repo,read:user
        user-agent: ${GITHUB_USER_AGENT}
gcp:
  http:
    client:
      auth:
        patterns:
          - /analytics/**
