name: Windows Native CLI
on:
  push:
    branches:
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - '[1-9]+.[0-9]+.x'
jobs:
  build:
    name: Builds Windows Native CLI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup GraalVM CE
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.3.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build JAR File
        shell: powershell
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
        run: ./gradlew grails-cli:copyShadowJar --no-daemon
      - name: Build Native Image
        shell: powershell
        run: native-image.cmd --no-fallback --allow-incomplete-classpath -cp build/libs/cli.jar
      - name: Verify Build (Powershell)
        shell: powershell
        run: ./grails.exe --version
      - name: Verify Create App (Powershell)
        run: ./grails.exe create-app test
      - name: Verify Build (CMD)
        shell: cmd
        run: grails --version
      - name: Verify Create App (CMD)
        shell: cmd
        run: grails create-app test2
      - name: ZIP Archive
        run: |
          New-Item "./grails-win-amd64-snapshot/bin" -ItemType Directory -ea 0
          Move-Item -Path ./grails.exe -Destination "./grails-win-amd64-snapshot/bin"
          Copy-Item "./LICENSE" -Destination "./grails-win-amd64-snapshot"
          Compress-Archive -Path "./grails-win-amd64-snapshot" -Update -DestinationPath ./grails-win-amd64-snapshot.zip
      - name: Publish artifact
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/1.0.x'
        uses: actions/upload-artifact@v3
        with:
          name: grails-win-amd64-snapshot
          path: ./grails-win-amd64-snapshot.zip
